# Generated by Django 4.0.4 on 2022-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_window_standard_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='standard_size',
            field=models.CharField(blank=True, choices=[('4 x 4', '4 x 4'), ('4 x 6', '4 x 6'), ('6 x 8', '6 x 8')], max_length=100, null=True),
        ),
    ]
