# Generated by Django 4.0.4 on 2022-05-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_window_standard_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hanging_Cabinet',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.category')),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_size', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('myapp.category',),
        ),
    ]
