# Generated by Django 4.0.4 on 2022-05-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_hanging_cabinet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquarium',
            old_name='height',
            new_name='standard_size',
        ),
        migrations.RemoveField(
            model_name='aquarium',
            name='length',
        ),
        migrations.RemoveField(
            model_name='aquarium',
            name='width',
        ),
        migrations.RemoveField(
            model_name='build_in_cabinet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='build_in_cabinet',
            name='length',
        ),
        migrations.RemoveField(
            model_name='build_in_cabinet',
            name='width',
        ),
        migrations.RemoveField(
            model_name='door',
            name='height',
        ),
        migrations.RemoveField(
            model_name='door',
            name='width',
        ),
        migrations.RemoveField(
            model_name='hanging_cabinet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='hanging_cabinet',
            name='width',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
        migrations.RemoveField(
            model_name='window',
            name='length',
        ),
        migrations.RemoveField(
            model_name='window',
            name='width',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
